In [2]:
import pandas as pd
import uteis

In [27]:
root = str(uteis.openfile())
print (root)
df = pd.read_excel(root)

D:/Documentos/Documents/Pousada do Deck/Sistema elétrico/Mapa Sistema/Mapadefases.xlsx

In [29]:
arq = (root.split('/')[-1])
print(arq)
arqname = (arq.split('.xlsx')[0])
print (arqname)

Mapadefases.xlsx
Mapadefases

In [35]:
display(df.head())

,Ordem,Caixa,Fase,Disj,Disj Tipo,Carga,Cant,Unnamed: 7,Descrip,Watts,watt seg,Lig/desl,wsimul,Voltsimul,Amp
0,0,Cuadro Prin,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Quarto 1,1,2,30CA,Chuveiro,1.0,NaN,Lorenzetti Maxi Ducha Ultra,4600,5000.0,0.0,2500.0,210.0,0.0
2,1,Quarto 1,1,1,?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Quarto 1,1,4,15CA,Air,1.0,NaN,TCL sim placa,815,1500.0,NaN,1500.0,210.0,0.0
4,1,Quarto 1,1,3,15CA,Ventilador,1.0,NaN,Ventisal,100,100.0,NaN,NaN,NaN,NaN

In [37]:
display(df.dtypes)

Ordem           int64
Caixa          object
Fase           object
Disj           object
Disj Tipo      object
Carga          object
Cant          float64
Unnamed: 7    float64
Descrip        object
Watts          object
watt seg      float64
Lig/desl      float64
wsimul        float64
Voltsimul     float64
Amp           float64
dtype: object

In [728]:
display(df.columns)

Index(['symbol', 'fechaIni', 'fechaFin', 'k', 'd', 'smoth', 'day mult',
       'sem mult', 'cantSeñales', 'long index', 'maxLongAcu', 'minLongAcu',
       'minLong', 'short index', 'maxShortAcu', 'minShortAcu', 'minShort',
       'long+short', 'maxInd', 'minInd'],
      dtype='object')

In [39]:
import sqlite3
# Conecte-se ao banco de dados (ou crie um novo arquivo de banco de dados)
conexao = sqlite3.connect('dbPousada.db')
#Gerar nome da tabula SQLite
tabname = str('dbtb_' + arqname)
# Exportar o DataFrame para uma tabela no banco de dados SQLite
df.to_sql(tabname, conexao, if_exists='append', index=False)
# Fechar a conexão
conexao.close()

In [51]:
# Conectar ao banco de dados SQLite
conn = sqlite3.connect('dbPousada.db')
sqltabname = str('SELECT * FROM ' +'"'+tabname+'"')

print (sqltabname)
# Ler a tabela para um DataFrame do pandas
tabsql = pd.read_sql(sqltabname, conn)
# Fechar a conexão
conn.close()
#apresenta alongamento max de dados e columnas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

# Mostrar o DataFrame
display (tabsql)

SELECT * FROM "dbtb_Mapadefases"

,Ordem,Caixa,Fase,Disj,Disj Tipo,Carga,Cant,Unnamed: 7,Descrip,Watts,watt seg,Lig/desl,wsimul,Voltsimul,Amp
0,0,Cuadro Prin,1,1,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN
1,1,Quarto 1,1,2,30CA,Chuveiro,1.0,None,Lorenzetti Maxi Ducha Ultra,4600,5000.0,0.0,2500.0,210.0,0.0
2,1,Quarto 1,1,1,?,None,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN
3,1,Quarto 1,1,4,15CA,Air,1.0,None,TCL sim placa,815,1500.0,NaN,1500.0,210.0,0.0
4,1,Quarto 1,1,3,15CA,Ventilador,1.0,None,Ventisal,100,100.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,0,Cuadro Prin,2,2,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN
130,0,Cuadro Prin,3,3,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN
131,21,Sala,None,None,None,Sandwichera,1.0,None,None,None,1200.0,NaN,NaN,NaN,NaN
132,22,Ferramentas,?,?,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN
133,25,Recep,2,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN